### ISSUE TITLE
'baf reset database raw' does not start 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#60]
```
D:\git\cbr-db\cbr_db>baf reset database raw
Database: dbf_db
Deleted existing database and created empty database under same name.
Database: dbf_db
Calling: ['mysql', '-utest_user', '-ptest_password', '--database', 'dbf_db', '--execute', 'source C:/Users/B7E3~1/AppData/Local/Temp/cbr-db/dbf_db.sql']
Traceback (most recent call last):
  File "C:\Users\Евгений\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Евгений\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\git\cbr-db\cbr_db\bankform.py", line 255, in <module>
    main(sys.argv[1:])
  File "D:\git\cbr-db\cbr_db\bankform.py", line 167, in main
    general_database_operations(arg, db_name)
  File "D:\git\cbr-db\cbr_db\bankform.py", line 158, in general_database_operations
    load_db_from_dump(db_name)
  File "D:\git\cbr-db\cbr_db\commands.py", line 50, in load_db_from_dump
    source_sql_file(patch_sql_file(path), db_name)
  File "D:\git\cbr-db\cbr_db\database\process.py", line 69, in source_sql_file
    run_sql_string(command, database=db_name)
  File "D:\git\cbr-db\cbr_db\database\process.py", line 63, in run_sql_string
    run_process(cmdline)
  File "D:\git\cbr-db\cbr_db\database\process.py", line 152, in run_process
    subprocess.check_call(cmdline, shell=shell, stdout=stdout, stderr=stderr)
  File "C:\Users\Евгений\Anaconda3\lib\subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Евгений\Anaconda3\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Евгений\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Евгений\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

**Comment by alexanderlukanin13** [comment]
MySQL is not in PATH. I'll add auto-detect feature for MySQL path.

**Comment by epogrebnyak** [comment]
I was adding mysl path though to settings.py
29 февр. 2016 г. 13:37 пользователь "Alexander Lukanin" <
notifications@github.com> написал:

**Comment by alexanderlukanin13** [comment]
@epogrebnyak Please try the latest `master`

**Comment by epogrebnyak** [comment]
Please see [sample.err](https://github.com/epogrebnyak/cbr-db/blob/master/cbr_db/sample.err) for errors running ```sample.bat```

Also referenced as #61

**Comment by alexanderlukanin13** [comment]
@epogrebnyak I think we can close this, original error is gone and we have a separate issue #61 for MySQL login problem.
